/* ══════════════════════════════════════════════════════════════════════════════
   PERFIL MEJORADO Y PROGRAMA DE LEALTAD v2.0 - DISEÑO MODERNO
   ══════════════════════════════════════════════════════════════════════════════ */
(function(){
const Loyalty={levels:[{name:'Bronce',minPoints:0,color:'#cd7f32',bg:'#fef3c7',glow:'rgba(205,127,50,0.3)',icon:'🥉',benefits:['Acceso básico','Soporte estándar']},{name:'Plata',minPoints:500,color:'#9ca3af',bg:'#f3f4f6',glow:'rgba(156,163,175,0.3)',icon:'🥈',benefits:['Acceso prioritario','Soporte rápido','5% descuento']},{name:'Oro',minPoints:2000,color:'#f59e0b',bg:'#fef3c7',glow:'rgba(245,158,11,0.3)',icon:'🥇',benefits:['Acceso VIP','Soporte express','10% descuento']},{name:'Diamante',minPoints:5000,color:'#06b6d4',bg:'#ecfeff',glow:'rgba(6,182,212,0.3)',icon:'💎',benefits:['Todo incluido','20% descuento','Acceso anticipado']}],calculateLevel:function(p){var l=this.levels[0];for(var i=0;i<this.levels.length;i++)if(p>=this.levels[i].minPoints)l=this.levels[i];return l;},getNextLevel:function(p){for(var i=0;i<this.levels.length;i++)if(p<this.levels[i].minPoints)return this.levels[i];return null;},getProgress:function(p){var cl=this.calculateLevel(p),ci=this.levels.indexOf(cl),nl=this.levels[ci+1];if(!nl)return 100;return Math.min(100,Math.round(((p-cl.minPoints)/(nl.minPoints-cl.minPoints))*100));},calcPoints:function(u,o){var pts=0;if(o&&o.length>0)o.forEach(function(r){pts+=Math.floor((Number(r.amount)||0)/1000)*10;});if(u.loyalty_points)pts=u.loyalty_points;return pts;}};
const Achievements={list:[{id:'first_buy',name:'Primera',icon:'🛒',cond:function(u,o){return o.length>=1;}},{id:'power_buyer',name:'Pro',icon:'💪',cond:function(u,o){return o.length>=10;}},{id:'big_spender',name:'Gastador',icon:'💰',cond:function(u,o){return o.reduce(function(s,i){return s+Number(i.amount||0);},0)>=500000;}},{id:'loyal',name:'Fiel',icon:'⭐',cond:function(u){if(!u.created_at)return false;return (Date.now()-new Date(u.created_at))/(1000*60*60*24)>=30;}},{id:'golden',name:'Oro',icon:'🥇',cond:function(u,o){return Loyalty.calculateLevel(Loyalty.calcPoints(u,o)).name==='Oro';}},{id:'vip',name:'VIP',icon:'👑',cond:function(u,o){return Loyalty.calculateLevel(Loyalty.calcPoints(u,o)).name==='Diamante';}}],getUnlocked:function(u,o){return this.list.filter(function(a){return a.cond(u,o);});}};
const AvatarColors=['#ef4444','#f97316','#eab308','#22c55e','#06b6d4','#3b82f6','#8b5cf6','#ec4899','#6366f1','#14b8a6'];
const AvatarEmojis=['😀','👨','👩','🧑','👴','👵','🧔','👱','🦸','🎯'];
var tempColor='#3b82f6',tempEmoji='😀';
function fmtMoney(a){return new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',minimumFractionDigits:0}).format(a||0);}
function daysSince(d){if(!d)return 0;return Math.floor((Date.now()-new Date(d))/(1000*60*60*24));}
function esc(s){if(s==null)return'';var d=document.createElement('div');d.textContent=String(s);return d.innerHTML;}
function openProfileImproved(){var u=state.user||{},o=state.orders||[],r=state.reports||[],pts=Loyalty.calcPoints(u,o),lvl=Loyalty.calculateLevel(pts),nextLvl=Loyalty.getNextLevel(pts),prog=Loyalty.getProgress(pts),spent=o.reduce(function(s,i){return s+Number(i.amount||0);},0),unlocked=Achievements.getUnlocked(u,o),days=daysSince(u.created_at);
var h='<div style="background:linear-gradient(180deg,#fff 0%,#f8fafc 100%);border-radius:20px 20px 0 0;overflow:hidden">';
h+='<div style="background:linear-gradient(135deg,'+lvl.color+' 0%,#1e293b 100%);padding:32px 24px 48px;text-align:center;position:relative">';
h+='<div style="position:absolute;top:12px;right:12px"><button onclick="closeModal()" style="width:36px;height:36px;border-radius:50%;background:rgba(255,255,255,0.15);border:none;color:#fff;font-size:18px;cursor:pointer;display:flex;align-items:center;justify-content:center">×</button></div>';
h+='<div style="width:100px;height:100px;border-radius:50%;background:linear-gradient(135deg,'+tempColor+','+tempColor+'dd);display:grid;place-items:center;font-size:44px;color:#fff;margin:0 auto 16px;box-shadow:0 8px 32px '+lvl.glow+',0 0 0 4px rgba(255,255,255,0.2);cursor:pointer;transition:transform 0.3s" onclick="openAvatarSelector()" onmouseover="this.style.transform=\'scale(1.05)\'" onmouseout="this.style.transform=\'scale(1)\'">'+tempEmoji+'</div>';
h+='<h2 style="margin:0 0 4px;font-size:26px;font-weight:800;color:#fff;text-shadow:0 2px 4px rgba(0,0,0,0.1)">'+esc(u.name||'Usuario')+'</h2>';
h+='<p style="margin:0 0 16px;font-size:13px;color:rgba(255,255,255,0.8)">'+esc(u.email||'')+'</p>';
h+='<div style="display:inline-flex;align-items:center;gap:10px;padding:12px 20px;background:rgba(255,255,255,0.2);backdrop-filter:blur(10px);border-radius:50px;border:1px solid rgba(255,255,255,0.3)">';
h+='<span style="font-size:20px">'+lvl.icon+'</span><span style="font-size:14px;font-weight:800;color:#fff">'+lvl.name+'</span>';
h+='<span style="width:1px;height:20px;background:rgba(255,255,255,0.4)"></span>';
h+='<span style="font-size:16px;font-weight:800;color:#fff">'+pts.toLocaleString()+' pts</span></div></div>';
h+='<div style="padding:0 20px;margin-top:-24px;position:relative">';
if(nextLvl){h+='<div style="background:#fff;border-radius:16px;padding:20px;box-shadow:0 4px 20px rgba(0,0,0,0.08);margin-bottom:16px">';
h+='<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px">';
h+='<div style="display:flex;align-items:center;gap:8px"><span style="font-size:24px">'+lvl.icon+'</span><span style="font-size:14px;font-weight:700;color:#64748b">'+lvl.name+'</span></div>';
h+='<div style="display:flex;align-items:center;gap:8px"><span style="font-size:24px">'+nextLvl.icon+'</span><span style="font-size:14px;font-weight:700;color:'+nextLvl.color+'">'+nextLvl.name+'</span></div></div>';
h+='<div style="height:12px;background:#e2e8f0;border-radius:6px;overflow:hidden;position:relative">';
h+='<div style="height:100%;width:'+prog+'%;background:linear-gradient(90deg,'+lvl.color+','+nextLvl.color+');border-radius:6px;transition:width 0.5s ease"></div></div>';
h+='<div style="text-align:center;margin-top:12px;font-size:13px;color:#64748b"><strong style="color:'+nextLvl.color+'">'+(nextLvl.minPoints-pts).toLocaleString()+'</strong> puntos para el siguiente nivel</div></div>';}else{h+='<div style="background:linear-gradient(135deg,'+lvl.color+','+nextLvl.color+');border-radius:16px;padding:24px;text-align:center;margin-bottom:16px;box-shadow:0 4px 20px '+lvl.glow+'">';
h+='<span style="font-size:48px;display:block;margin-bottom:8px">🎉</span>';
h+='<div style="font-size:16px;font-weight:800;color:#fff">¡Nivel Máximo Alcanzado!</div>';
h+='<div style="font-size:12px;color:rgba(255,255,255,0.8);margin-top:4px">Eres parte del club exclusivo</div></div>';}
h+='<div style="background:#fff;border-radius:16px;padding:20px;box-shadow:0 4px 20px rgba(0,0,0,0.08);margin-bottom:16px">';
h+='<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:12px;text-align:center">';
h+='<div><div style="font-size:28px;font-weight:900;color:#3b82f6">'+o.length+'</div><div style="font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:0.05em;margin-top:4px">Compras</div></div>';
h+='<div><div style="font-size:28px;font-weight:900;color:#10b981">'+fmtMoney(spent).replace('COP','').trim()+'</div><div style="font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:0.05em;margin-top:4px">Gastado</div></div>';
h+='<div><div style="font-size:28px;font-weight:900;color:#f59e0b">'+unlocked.length+'</div><div style="font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:0.05em;margin-top:4px">Logros</div></div>';
h+='<div><div style="font-size:28px;font-weight:900;color:#8b5cf6">'+days+'</div><div style="font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:0.05em;margin-top:4px">Días</div></div></div></div>';
h+='<div style="background:#fff;border-radius:16px;padding:20px;box-shadow:0 4px 20px rgba(0,0,0,0.08);margin-bottom:16px">';
h+='<div style="font-size:14px;font-weight:700;color:#1e293b;margin-bottom:12px;display:flex;align-items:center;gap:8px"><span style="font-size:18px">'+lvl.icon+'</span> Beneficios '+lvl.name+'</div>';
h+='<div style="display:flex;flex-wrap:wrap;gap:8px">';
lvl.benefits.forEach(function(b){h+='<span style="padding:8px 14px;background:'+lvl.bg+';color:'+lvl.color+';border-radius:20px;font-size:12px;font-weight:600">✓ '+b+'</span>';});h+='</div></div>';
h+='<div style="background:#fff;border-radius:16px;padding:20px;box-shadow:0 4px 20px rgba(0,0,0,0.08);margin-bottom:16px">';
h+='<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px"><div style="font-size:14px;font-weight:700;color:#1e293b">🏆 Mis Logros</div><div style="font-size:12px;font-weight:600;color:#64748b;background:#f1f5f9;padding:4px 12px;border-radius:20px">'+unlocked.length+'/'+Achievements.list.length+'</div></div>';
h+='<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:12px">';
Achievements.list.forEach(function(a){var done=unlocked.some(function(x){return x.id===a.id;});h+='<div style="background:'+(done?lvl.bg:'#f8fafc')+';border-radius:14px;padding:16px 12px;text-align:center;border:2px solid '+(done?lvl.color:'#e2e8f0')+';transition:all 0.2s;cursor:pointer" onmouseover="this.style.transform=\'translateY(-2px)\'" onmouseout="this.style.transform=\'translateY(0)\'">';
h+='<div style="font-size:32px;margin-bottom:6px;filter:'+(done?'none':'grayscale(1) opacity(0.5)')+'">'+a.icon+'</div>';
h+='<div style="font-size:11px;font-weight:700;color:'+(done?lvl.color:'#94a3b8')+'">'+a.name+'</div></div>';});h+='</div></div>';
h+='<div style="background:#fff;border-radius:16px;padding:20px;box-shadow:0 4px 20px rgba(0,0,0,0.08);margin-bottom:20px">';
h+='<div style="font-size:14px;font-weight:700;color:#1e293b;margin-bottom:16px">📋 Mi Cuenta</div>';
h+='<div style="display:flex;justify-content:space-between;align-items:center;padding:12px 0;border-bottom:1px solid #f1f5f9"><span style="font-size:13px;color:#64748b">📱 Teléfono</span><span style="font-size:13px;font-weight:700;color:#1e293b">'+(u.phone||'3102765347')+'</span></div>';
h+='<div style="display:flex;justify-content:space-between;align-items:center;padding:12px 0;border-bottom:1px solid #f1f5f9"><span style="font-size:13px;color:#64748b">📍 Ubicación</span><span style="font-size:13px;font-weight:700;color:#1e293b">'+(u.location||'Bogotá, Colombia')+'</span></div>';
h+='<div style="display:flex;justify-content:space-between;align-items:center;padding:12px 0;border-bottom:1px solid #f1f5f9"><span style="font-size:13px;color:#64748b">👤 Miembro desde</span><span style="font-size:13px;font-weight:700;color:#1e293b">'+(u.created_at?new Date(u.created_at).toLocaleDateString('es-CO',{year:'numeric',month:'short'}):'Hace '+days+' días')+'</span></div>';
h+='<div style="display:flex;justify-content:space-between;align-items:center;padding:12px 0"><span style="font-size:13px;color:#64748b">✅ Estado</span><span style="font-size:12px;font-weight:700;color:#10b981;background:#dcfce7;padding:6px 14px;border-radius:20px">'+(u.status||'Activo')+'</span></div></div>';
h+='<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;padding-bottom:20px">';
h+='<button onclick="openAvatarSelector()" style="padding:16px;border:2px solid #e2e8f0;border-radius:14px;background:#fff;font-weight:700;font-size:13px;color:#1e293b;cursor:pointer;transition:all 0.2s;display:flex;align-items:center;justify-content:center;gap:8px" onmouseover="this.style.borderColor=\'#3b82f6\';this.style.color=\'#3b82f6\'" onmouseout="this.style.borderColor=\'#e2e8f0\';this.style.color=\'#1e293b\'">🎨 Avatar</button>';
h+='<button onclick="openEditProfile()" style="padding:16px;border:2px solid #e2e8f2;border-radius:14px;background:#fff;font-weight:700;font-size:13px;color:#1e293b;cursor:pointer;transition:all 0.2s;display:flex;align-items:center;justify-content:center;gap:8px" onmouseover="this.style.borderColor=\'#3b82f6\';this.style.color=\'#3b82f6\'" onmouseout="this.style.borderColor=\'#e2e8f0\';this.style.color=\'#1e293b\'">✏️ Editar</button></div>';
h+='<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;padding-bottom:24px">';
h+='<button onclick="toggleDark()" style="padding:16px;border:none;border-radius:14px;background:#f1f5f9;font-weight:700;font-size:13px;color:#64748b;cursor:pointer;transition:all 0.2s;display:flex;align-items:center;justify-content:center;gap:8px" onmouseover="this.style.background=\'#e2e8f0\'" onmouseout="this.style.background=\'#f1f5f9\'">🌙 Cambiar tema</button>';
h+='<button onclick="logout()" style="padding:16px;border:none;border-radius:14px;background:linear-gradient(135deg,#ef4444,#dc2626);font-weight:700;font-size:13px;color:#fff;cursor:pointer;transition:all 0.2s;box-shadow:0 4px 14px rgba(239,68,68,0.3);display:flex;align-items:center;justify-content:center;gap:8px" onmouseover="this.style.transform=\'translateY(-1px)\';this.style.boxShadow=\'0 6px 20px rgba(239,68,68,0.4)\'" onmouseout="this.style.transform=\'translateY(0)\';this.style.boxShadow=\'0 4px 14px rgba(239,68,68,0.3)\'">🚪 Cerrar sesión</button></div></div></div>';
openModal(h);}
function openAvatarSelector(){var u=state.user||{},cOpt='';AvatarColors.forEach(function(c){cOpt+='<div onclick="setAvatarColor(\''+c+'\')" style="width:44px;height:44px;border-radius:50%;background:'+c+';cursor:pointer;border:4px solid '+(tempColor===c?'#1e293b':'transparent')+';transition:all 0.2s;box-shadow:0 2px 8px '+c+'44" onmouseover="this.style.transform=\'scale(1.1)\'" onmouseout="this.style.transform=\'scale(1)\'"></div>';});var eOpt='';AvatarEmojis.forEach(function(e){eOpt+='<div onclick="setAvatarEmoji(\''+e+'\')" style="width:50px;height:50px;border-radius:14px;background:#f8fafc;cursor:pointer;display:grid;place-items:center;font-size:26px;border:3px solid '+(tempEmoji===e?'#3b82f6':'#e2e8f0')+';transition:all 0.2s" onmouseover="this.style.transform=\'scale(1.1)\';this.style.borderColor=\'#3b82f6\'" onmouseout="this.style.transform=\'scale(1)\';this.style.borderColor='+(tempEmoji===e?'#3b82f6':'#e2e8f0')+''>'+e+'</div>';});openModal('<div style="padding:8px"><h3 style="font-size:20px;font-weight:800;color:#1e293b;margin:0 0 4px;text-align:center">Elige tu Avatar</h3><p style="font-size:13px;color:#64748b;margin:0 0 24px;text-align:center">Personaliza cómo te ven los demás</p><div style="text-align:center;margin-bottom:28px"><div id="avatarPreview" style="width:120px;height:120px;border-radius:50%;background:linear-gradient(135deg,'+tempColor+','+tempColor+'dd);display:grid;place-items:center;font-size:56px;color:#fff;margin:0 auto;box-shadow:0 8px 32px '+tempColor+'44;transition:all 0.3s">'+tempEmoji+'</div></div><div style="margin-bottom:20px"><div style="font-size:13px;font-weight:700;color:#64748b;margin-bottom:12px;text-transform:uppercase;letter-spacing:0.05em">Color</div><div style="display:flex;flex-wrap:wrap;gap:12px;justify-content:center">'+cOpt+'</div></div><div style="margin-bottom:24px"><div style="font-size:13px;font-weight:700;color:#64748b;margin-bottom:12px;text-transform:uppercase;letter-spacing:0.05em">Emoji</div><div style="display:flex;flex-wrap:wrap;gap:10px;justify-content:center">'+eOpt+'</div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><button onclick="openProfileImproved()" style="padding:14px;border:2px solid #e2e8f0;border-radius:12px;background:#fff;font-weight:700;font-size:14px;color:#64748b;cursor:pointer">Cancelar</button><button onclick="saveAvatar()" style="padding:14px;border:none;border-radius:12px;background:linear-gradient(135deg,#3b82f6,#2563eb);font-weight:700;font-size:14px;color:#fff;cursor:pointer;box-shadow:0 4px 14px rgba(59,130,246,0.3)">Guardar</button></div></div>');}
function setAvatarColor(c){tempColor=c;var p=document.getElementById('avatarPreview');if(p){p.style.background='linear-gradient(135deg,'+c+','+c+'dd)';p.style.boxShadow='0 8px 32px '+c+'44';}}
function setAvatarEmoji(e){tempEmoji=e;var p=document.getElementById('avatarPreview');if(p)p.innerHTML=e;}
function saveAvatar(){var u=state.user||{};localStorage.setItem('userAvatar_'+u.id||u.email,JSON.stringify({emoji:tempEmoji,color:tempColor}));toast('Avatar actualizado ✨','ok');openProfileImproved();}
function openEditProfile(){var u=state.user||{};openModal('<div style="padding:8px"><h3 style="font-size:20px;font-weight:800;color:#1e293b;margin:0 0 4px">Editar Perfil</h3><p style="font-size:13px;color:#64748b;margin:0 0 24px">Actualiza tu información personal</p><div style="display:grid;gap:20px"><div><label style="font-size:12px;font-weight:700;color:#64748b;display:block;margin-bottom:8px;text-transform:uppercase;letter-spacing:0.05em">Nombre completo</label><input type="text" id="editName" value="'+esc(u.name||'')+'" placeholder="Tu nombre" style="width:100%;padding:14px 16px;border:2px solid #e2e8f0;border-radius:12px;font-size:15px;background:#fff;color:#1e293b;transition:border-color 0.2s" onfocus="this.style.borderColor=\'#3b82f6\'" onblur="this.style.borderColor=\'#e2e8f0\'"/></div><div><label style="font-size:12px;font-weight:700;color:#64748b;display:block;margin-bottom:8px;text-transform:uppercase;letter-spacing:0.05em">Teléfono</label><input type="tel" id="editPhone" value="'+esc(u.phone||'')+'" placeholder="3001234567" style="width:100%;padding:14px 16px;border:2px solid #e2e8f0;border-radius:12px;font-size:15px;background:#fff;color:#1e293b;transition:border-color 0.2s" onfocus="this.style.borderColor=\'#3b82f6\'" onblur="this.style.borderColor=\'#e2e8f0\'"/></div><div><label style="font-size:12px;font-weight:700;color:#64748b;display:block;margin-bottom:8px;text-transform:uppercase;letter-spacing:0.05em">Ubicación</label><input type="text" id="editLocation" value="'+esc(u.location||'')+'" placeholder="Ciudad, País" style="width:100%;padding:14px 16px;border:2px solid #e2e8f0;border-radius:12px;font-size:15px;background:#fff;color:#1e293b;transition:border-color 0.2s" onfocus="this.style.borderColor=\'#3b82f6\'" onblur="this.style.borderColor=\'#e2e8f0\'"/></div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:28px"><button onclick="openProfileImproved()" style="padding:14px;border:2px solid #e2e8f0;border-radius:12px;background:#fff;font-weight:700;font-size:14px;color:#64748b;cursor:pointer">Cancelar</button><button onclick="saveProfileChanges()" style="padding:14px;border:none;border-radius:12px;background:linear-gradient(135deg,#3b82f6,#2563eb);font-weight:700;font-size:14px;color:#fff;cursor:pointer;box-shadow:0 4px 14px rgba(59,130,246,0.3)">Guardar</button></div></div>');}
function saveProfileChanges(){var n=document.getElementById('editName')?.value?.trim();if(!n||n.length<3){toast('El nombre debe tener al menos 3 caracteres','bad');return;}state.user={...state.user,name:n,phone:document.getElementById('editPhone')?.value?.trim(),location:document.getElementById('editLocation')?.value?.trim()};localStorage.setItem('dsUser',JSON.stringify(state.user));toast('Perfil actualizado ✅','ok');renderApp();closeModal();}
window.openProfile=openProfileImproved;
console.log('✅ Perfil v2.0 - Diseño moderno cargado');
})();
