/* ══════════════════════════════════════════════════════════════════════════════
   PERFIL MEJORADO Y PROGRAMA DE LEALTAD v1.0
   ══════════════════════════════════════════════════════════════════════════════ */
(function(){
const Loyalty={levels:[{name:'Bronce',minPoints:0,color:'#cd7f32',bgColor:'rgba(205,127,50,.12)',icon:'🥉',benefits:['Acceso básico','Soporte estándar']},{name:'Plata',minPoints:500,color:'#c0c0c0',bgColor:'rgba(192,192,192,.12)',icon:'🥈',benefits:['Acceso prioritario','Soporte rápido','5% descuento']},{name:'Oro',minPoints:2000,color:'#ffd700',bgColor:'rgba(255,215,0,.12)',icon:'🥇',benefits:['Acceso VIP','Soporte express','10% descuento']},{name:'Diamante',minPoints:5000,color:'#b9f2ff',bgColor:'rgba(185,242,255,.12)',icon:'💎',benefits:['Todo incluido','Soporte 24/7','20% descuento']}],calculateLevel:function(p){var l=this.levels[0];for(var i=0;i<this.levels.length;i++)if(p>=this.levels[i].minPoints)l=this.levels[i];return l;},getNextLevel:function(p){for(var i=0;i<this.levels.length;i++)if(p<this.levels[i].minPoints)return this.levels[i];return null;},getProgress:function(p){var cl=this.calculateLevel(p),ci=this.levels.indexOf(cl),nl=this.levels[ci+1];if(!nl)return 100;return Math.min(100,Math.round(((p-cl.minPoints)/(nl.minPoints-cl.minPoints))*100));},calcPoints:function(u,o){var pts=0;if(o&&o.length>0)o.forEach(function(r){pts+=Math.floor((Number(r.amount)||0)/1000)*10;});if(u.loyalty_points)pts=u.loyalty_points;return pts;}};
const Achievements={list:[{id:'first_buy',name:'Primera Compra',icon:'🛒',cond:function(u,o){return o.length>=1;}},{id:'power_buyer',name:'Comprador Pro',icon:'💪',cond:function(u,o){return o.length>=10;}},{id:'big_spender',name:'Gran Gastador',icon:'💰',cond:function(u,o){return o.reduce(function(s,i){return s+Number(i.amount||0);},0)>=500000;}},{id:'loyal',name:'Cliente Fiel',icon:'⭐',cond:function(u){if(!u.created_at)return false;return (Date.now()-new Date(u.created_at))/(1000*60*60*24)>=30;}},{id:'golden',name:'Nivel Oro',icon:'🥇',cond:function(u,o){return Loyalty.calculateLevel(Loyalty.calcPoints(u,o)).name==='Oro';}},{id:'vip',name:'VIP',icon:'👑',cond:function(u,o){return Loyalty.calculateLevel(Loyalty.calcPoints(u,o)).name==='Diamante';}}],getUnlocked:function(u,o){return this.list.filter(function(a){return a.cond(u,o);});}};
const AvatarColors=['#ef4444','#f97316','#eab308','#22c55e','#06b6d4','#3b82f6','#8b5cf6','#ec4899'];
const AvatarEmojis=['👤','👨','👩','🧑','👴','👵','🏅','⭐'];
var tempColor='#3b82f6',tempEmoji='👤';
function fmtMoney(a){return new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',minimumFractionDigits:0}).format(a||0);}
function daysSince(d){if(!d)return 0;return Math.floor((Date.now()-new Date(d))/(1000*60*60*24));}
function esc(s){if(s==null)return'';var d=document.createElement('div');d.textContent=String(s);return d.innerHTML;}
function openProfileImproved(){var u=state.user||{},o=state.orders||[],r=state.reports||[],pts=Loyalty.calcPoints(u,o),lvl=Loyalty.calculateLevel(pts),nextLvl=Loyalty.getNextLevel(pts),prog=Loyalty.getProgress(pts),spent=o.reduce(function(s,i){return s+Number(i.amount||0);},0),unlocked=Achievements.getUnlocked(u,o),days=daysSince(u.created_at);
var h='<div style="background:linear-gradient(135deg,'+lvl.color+'22,'+lvl.color+'11);padding:24px 20px;margin:-20px -20px 24px;text-align:center;position:relative">';
h+='<button onclick="closeModal()" style="position:absolute;top:12px;right:12px;width:32px;height:32px;border-radius:50%;border:1px solid '+lvl.color+'33;background:'+lvl.color+'11;color:'+lvl.color+';font-size:16px;cursor:pointer">×</button>';
h+='<div style="width:90px;height:90px;border-radius:50%;background:linear-gradient(135deg,'+tempColor+','+tempColor+'aa);display:grid;place-items:center;font-size:36px;color:#fff;border:3px solid rgba(255,255,255,.3);margin:0 auto 12px;box-shadow:0 4px 20px rgba(0,0,0,.15);cursor:pointer" onclick="openAvatarSelector()">'+tempEmoji+'</div>';
h+='<h2 style="margin:0 0 4px;font-size:22px;font-weight:900">'+esc(u.name||'Usuario')+'</h2>';
h+='<p style="margin:0 0 8px;color:var(--muted);font-size:13px">'+esc(u.email||'')+'</p>';
h+='<span style="display:inline-flex;align-items:center;gap:8px;padding:8px 16px;border-radius:20px;font-size:12px;font-weight:800;background:'+lvl.bgColor+';color:'+lvl.color+';border:2px solid '+lvl.color+'33">'+lvl.icon+' '+lvl.name+' <span style="opacity:.7">•</span> '+pts.toLocaleString()+' pts</span></div>';
if(nextLvl){h+='<div style="background:'+lvl.bgColor+';border-radius:12px;padding:16px;margin-bottom:20px"><div style="display:flex;justify-content:space-between;margin-bottom:10px;font-size:12px;font-weight:700;color:var(--muted)"><span>'+lvl.icon+' '+lvl.name+'</span><span style="color:'+nextLvl.color+'">'+nextLvl.icon+' '+nextLvl.name+'</span></div>';
h+='<div style="height:8px;background:rgba(0,0,0,.08);border-radius:4px"><div style="height:100%;width:'+prog+'%;background:linear-gradient(90deg,'+lvl.color+','+nextLvl.color+');border-radius:4px;transition:width .5s"></div></div>';
h+='<div style="text-align:center;margin-top:8px;font-size:11px;color:var(--muted)"><strong>'+(nextLvl.minPoints-pts)+'</strong> puntos para '+nextLvl.name+'</div></div>';}else{h+='<div style="background:'+lvl.bgColor+';border-radius:12px;padding:16px;margin-bottom:20px;text-align:center;border:2px solid '+lvl.color+'33"><span style="font-size:32px">🎉</span><div style="font-size:14px;font-weight:800;color:'+lvl.color+';margin-top:8px">¡Nivel Máximo!</div></div>';}
h+='<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:20px">';
h+='<div style="background:var(--soft);border-radius:12px;padding:14px;text-align:center;border:1px solid var(--line)"><div style="font-size:20px;font-weight:900;color:var(--blue)">'+o.length+'</div><div style="font-size:10px;color:var(--muted);margin-top:4px">Compras</div></div>';
h+='<div style="background:var(--soft);border-radius:12px;padding:14px;text-align:center;border:1px solid var(--line)"><div style="font-size:20px;font-weight:900;color:var(--ok)">'+fmtMoney(spent).replace('COP','').trim()+'</div><div style="font-size:10px;color:var(--muted);margin-top:4px">Gastado</div></div>';
h+='<div style="background:var(--soft);border-radius:12px;padding:14px;text-align:center;border:1px solid var(--line)"><div style="font-size:20px;font-weight:900;color:var(--warn)">'+unlocked.length+'</div><div style="font-size:10px;color:var(--muted);margin-top:4px">Logros</div></div>';
h+='<div style="background:var(--soft);border-radius:12px;padding:14px;text-align:center;border:1px solid var(--line)"><div style="font-size:20px;font-weight:900;color:var(--purple)">'+days+'</div><div style="font-size:10px;color:var(--muted);margin-top:4px">Días</div></div></div>';
h+='<div style="margin-bottom:20px"><h3 style="font-size:13px;font-weight:800;margin:0 0 12px">'+lvl.icon+' Beneficios '+lvl.name+'</h3><div style="display:flex;flex-wrap:wrap;gap:8px">';
lvl.benefits.forEach(function(b){h+='<span style="padding:6px 12px;background:'+lvl.bgColor+';color:'+lvl.color+';border-radius:20px;font-size:11px;font-weight:700">✓ '+b+'</span>';});h+='</div></div>';
h+='<div style="margin-bottom:20px"><h3 style="font-size:13px;font-weight:800;margin:0 0 12px">🏆 Logros <span style="margin-left:auto;font-size:11px;color:var(--muted)">'+unlocked.length+'/'+Achievements.list.length+'</span></h3><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px">';
Achievements.list.forEach(function(a){var done=unlocked.some(function(x){return x.id===a.id;});h+='<div style="background:var(--soft);border-radius:12px;padding:12px;text-align:center;opacity:'+(done?1:0.5)+';border:1px solid '+(done?'var(--ok)':'var(--line)');h+='"><div style="font-size:24px;margin-bottom:4px'+(done?'':';filter:grayscale(1)')+'>'+a.icon+'</div><div style="font-size:10px;font-weight:700">'+a.name+'</div></div>';});h+='</div></div>';
h+='<div style="background:var(--soft);border-radius:14px;padding:16px;margin-bottom:20px;border:1px solid var(--line)"><h3 style="font-size:13px;font-weight:800;margin:0 0 12px">📋 Información</h3>';
h+='<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid var(--line)"><span style="font-size:12px;color:var(--muted)">Teléfono</span><span style="font-size:13px;font-weight:700">'+(u.phone||'3102765347')+'</span></div>';
h+='<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid var(--line)"><span style="font-size:12px;color:var(--muted)">Ubicación</span><span style="font-size:13px;font-weight:700">'+(u.location||'Bogotá, Colombia')+'</span></div>';
h+='<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid var(--line)"><span style="font-size:12px;color:var(--muted)">Miembro desde</span><span style="font-size:13px;font-weight:700">'+(u.created_at?new Date(u.created_at).toLocaleDateString('es-CO',{year:'numeric',month:'long',day:'numeric'}):'Hace '+days+' días')+'</span></div>';
h+='<div style="display:flex;justify-content:space-between;padding:10px 0"><span style="font-size:12px;color:var(--muted)">Estado</span><span style="padding:4px 10px;background:rgba(16,185,129,.12);color:#10b981;border-radius:20px;font-size:11px;font-weight:700">● '+(u.status||'Activo')+'</span></div></div>';
h+='<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">';
h+='<button onclick="openAvatarSelector()" style="padding:14px;border:1.5px solid var(--line);border-radius:12px;background:var(--panel);font-weight:800;font-size:12px;cursor:pointer">🎨 Avatar</button>';
h+='<button onclick="openEditProfile()" style="padding:14px;border:1.5px solid var(--line);border-radius:12px;background:var(--panel);font-weight:800;font-size:12px;cursor:pointer">✏️ Editar</button></div>';
h+='<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px">';
h+='<button onclick="toggleDark()" style="padding:14px;border:1.5px solid var(--line);border-radius:12px;background:var(--panel);font-weight:800;font-size:12px;cursor:pointer">🌙 Tema</button>';
h+='<button onclick="logout()" style="padding:14px;border:0;border-radius:12px;background:linear-gradient(135deg,#ef4444,#dc2626);color:#fff;font-weight:800;font-size:12px;cursor:pointer;box-shadow:0 4px 12px rgba(239,68,68,.25)">🚪 Cerrar</button></div>';
openModal(h);}
function openAvatarSelector(){var cOpt='';AvatarColors.forEach(function(c){cOpt+='<div onclick="setAvatarColor(\''+c+'\')" style="width:36px;height:36px;border-radius:50%;background:'+c+';cursor:pointer;border:3px solid '+(tempColor===c?'var(--text)':'transparent')+';transition:all .15s"></div>';});var eOpt='';AvatarEmojis.forEach(function(e){eOpt+='<div onclick="setAvatarEmoji(\''+e+'\')" style="width:44px;height:44px;border-radius:12px;background:var(--soft);cursor:pointer;display:grid;place-items:center;font-size:22px;border:2px solid var(--line)">'+e+'</div>';});openModal('<div style="padding:4px"><h3 style="font-size:16px;font-weight:800;margin:0 0 4px">Personaliza tu Avatar</h3><p style="font-size:12px;color:var(--muted);margin:0 0 20px">Elige un color y emoji</p><div style="text-align:center;margin-bottom:24px"><div id="avatarPreview" style="width:100px;height:100px;border-radius:50%;background:linear-gradient(135deg,'+tempColor+','+tempColor+'aa);display:grid;place-items:center;font-size:48px;color:#fff;border:3px solid rgba(255,255,255,.3);margin:0 auto">'+tempEmoji+'</div></div><div style="margin-bottom:16px"><label style="font-size:12px;font-weight:700;color:var(--muted);display:block;margin-bottom:10px">Color</label><div style="display:flex;flex-wrap:wrap;gap:10px;justify-content:center">'+cOpt+'</div></div><div style="margin-bottom:20px"><label style="font-size:12px;font-weight:700;color:var(--muted);display:block;margin-bottom:10px">Emoji</label><div style="display:flex;flex-wrap:wrap;gap:8px;justify-content:center">'+eOpt+'</div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><button onclick="openProfileImproved()" class="ghost" style="padding:12px;border-radius:10px;font-weight:700">Cancelar</button><button onclick="saveAvatar()" class="primary" style="padding:12px;border-radius:10px;font-weight:700">Guardar</button></div></div>');}
function setAvatarColor(c){tempColor=c;var p=document.getElementById('avatarPreview');if(p)p.innerHTML='<div style="width:100px;height:100px;border-radius:50%;background:linear-gradient(135deg,'+c+','+c+'aa);display:grid;place-items:center;font-size:48px;color:#fff;border:3px solid rgba(255,255,255,.3)">'+tempEmoji+'</div>';}
function setAvatarEmoji(e){tempEmoji=e;var p=document.getElementById('avatarPreview');if(p)p.innerHTML='<div style="width:100px;height:100px;border-radius:50%;background:linear-gradient(135deg,'+tempColor+','+tempColor+'aa);display:grid;place-items:center;font-size:48px;color:#fff;border:3px solid rgba(255,255,255,.3)">'+e+'</div>';}
function saveAvatar(){var u=state.user||{};localStorage.setItem('userAvatar_'+u.id||u.email,JSON.stringify({emoji:tempEmoji,color:tempColor}));toast('Avatar actualizado ✨','ok');openProfileImproved();}
function openEditProfile(){var u=state.user||{};openModal('<div style="padding:4px"><h3 style="font-size:16px;font-weight:800;margin:0 0 4px">Editar Perfil</h3><p style="font-size:12px;color:var(--muted);margin:0 0 20px">Actualiza tu información</p><div style="display:grid;gap:16px"><div><label style="font-size:12px;font-weight:700;color:var(--muted);display:block;margin-bottom:6px">Nombre</label><input type="text" id="editName" value="'+esc(u.name||'')+'" style="width:100%;padding:12px;border:1.5px solid var(--line);border-radius:10px;background:var(--panel)"/></div><div><label style="font-size:12px;font-weight:700;color:var(--muted);display:block;margin-bottom:6px">Teléfono</label><input type="tel" id="editPhone" value="'+esc(u.phone||'')+'" style="width:100%;padding:12px;border:1.5px solid var(--line);border-radius:10px;background:var(--panel)"/></div><div><label style="font-size:12px;font-weight:700;color:var(--muted);display:block;margin-bottom:6px">Ubicación</label><input type="text" id="editLocation" value="'+esc(u.location||'')+'" style="width:100%;padding:12px;border:1.5px solid var(--line);border-radius:10px;background:var(--panel)"/></div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:24px"><button onclick="openProfileImproved()" class="ghost" style="padding:12px;border-radius:10px;font-weight:700">Cancelar</button><button onclick="saveProfileChanges()" class="primary" style="padding:12px;border-radius:10px;font-weight:700">Guardar</button></div></div>');}
function saveProfileChanges(){var n=document.getElementById('editName')?.value?.trim();if(!n||n.length<3){toast('El nombre debe tener al menos 3 caracteres','bad');return;}state.user={...state.user,name:n,phone:document.getElementById('editPhone')?.value?.trim(),location:document.getElementById('editLocation')?.value?.trim()};localStorage.setItem('dsUser',JSON.stringify(state.user));toast('Perfil actualizado ✅','ok');renderApp();closeModal();}
window.openProfile=openProfileImproved;
console.log('✅ Perfil mejorado y lealtad cargados');
})();
